[package]
name = "fpass"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.98"
argon2 = "0.5.3"
password-hash = "0.5.0"
rand = "0.8"
rand_core = "0.6"
serde = { version = "1.0.219", features=["derive"] }
serde_json = "1.0.140"
